name: API workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test Airflow
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install requirements
      run: pip install -r src/airflow/requirements.txt
    - name: Run tests and collect coverage
      run: pytest --cov=src.airflow.airqo_etl_utils --cov-report=xml
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
