name: API workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test Airflow
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
  
    - name: Run tests and collect coverage
      run: |
        cd src/airflow/airqo_etl_utils/tests_codecov
        pip install pytest
        pip install pytest-cov
        pytest --cov=./ --cov-report=xml
        
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: src/airflow/airqo_etl_utils/tests_codecov/coverage/reports/
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        files: ./coverage1.xml,./coverage2.xml,!./cache
        flags: unittests
        name: codecov-umbrella
        verbose: true

